script: rake ci
rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - rbx-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx-19mode # rbx on travis is out-of-date

notifications:
  irc: "irc.freenode.org#celluloid"
